version: 2

sources:
  - name: finance_raw
    database: PC_FIVETRAN_DB
    schema: FINANCE_RAW
    tables:
      - name: finance_invoices
        identifier: '"finance_invoices"'
      - name: finance_payments
        identifier: '"finance_payments"'
      - name: customers
        identifier: '"customers"'
